version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authninja_app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME="freeman_local"
      - MONGO_URL=""

